## Problem Definition and Context

YouTube (the world-famous video sharing website) maintains a list of the top trending videos on the platform. To determine the year’s top-trending videos, YouTube uses a combination of factors including measuring users interactions (number of views, shares, comments and likes).


This dataset includes several months (and counting) of data on daily trending YouTube videos. Data is included for the US, GB and CA regions (USA, Great Britain, and Canada respectively), with up to 200 listed trending videos per day.

Each region’s data is in a separate file. Data includes the video title, channel title, publish time, tags, views, likes and dislikes, description, and comment count.

## What analysis to be done? [20 Marks]

Based on the views, likes, dislikes, comment count, device a strategy strictly using only clustering, and Random Forest to classify the data onto optimum clusters. The strategy is subject to your interpretation of the data and use of tools. There is no right answer. The judgement on the model and startegy Should be based on a sound logical analysis.

First, you may have join the 3 datasets. Make sure to create an extra column of Country to distinguish the data.

As you will note there are you have create optimum clusters using silhouette's coefficient.

After the clusters are created, those clusters can be assigned a label through an extra column in the existing dataset.

Random Forest can then be used to create the classification model. Choose 80% Data randomly from the clustered Video datasets to train the model. Use rest to test and validate the model and test the accuracy. Remove the columns which are not useful for prediction.

#### Use of clustering for initial grouping [10 Marks]

#### Use of Random Forest to classify the model [5 Marks]

##### Proper Training, testing and Validation [5 Marks]

Merging 3 datasets + clustering

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df1 = pd.read_csv("drive/MyDrive/CAvideos.csv")

In [ ]:
df2 = pd.read_csv("drive/MyDrive/USvideos.csv")

In [ ]:
df3 = pd.read_csv("drive/MyDrive/GBvideos.csv")

In [ ]:
list(df1.columns)

['video_id',
 'trending_date',
 'title',
 'channel_title',
 'category_id',
 'publish_time',
 'tags',
 'views',
 'likes',
 'dislikes',
 'comment_count',
 'thumbnail_link',
 'comments_disabled',
 'ratings_disabled',
 'video_error_or_removed',
 'description']

In [ ]:
list(df2.columns)

['video_id',
 'trending_date',
 'title',
 'channel_title',
 'category_id',
 'publish_time',
 'tags',
 'views',
 'likes',
 'dislikes',
 'comment_count',
 'thumbnail_link',
 'comments_disabled',
 'ratings_disabled',
 'video_error_or_removed',
 'description']

In [ ]:
list(df3.columns)

['video_id',
 'trending_date',
 'title',
 'channel_title',
 'category_id',
 'publish_time',
 'tags',
 'views',
 'likes',
 'dislikes',
 'comment_count',
 'thumbnail_link',
 'comments_disabled',
 'ratings_disabled',
 'video_error_or_removed',
 'description']

In [ ]:
pd.isnull(df1).sum()

video_id                     0
trending_date                0
title                        0
channel_title                0
category_id                  0
publish_time                 0
tags                         0
views                        0
likes                        0
dislikes                     0
comment_count                0
thumbnail_link               0
comments_disabled            0
ratings_disabled             0
video_error_or_removed       0
description               1296
dtype: int64

In [ ]:
pd.isnull(df2).sum()

video_id                    0
trending_date               0
title                       0
channel_title               0
category_id                 0
publish_time                0
tags                        0
views                       0
likes                       0
dislikes                    0
comment_count               0
thumbnail_link              0
comments_disabled           0
ratings_disabled            0
video_error_or_removed      0
description               570
dtype: int64

In [ ]:
pd.isnull(df3).sum()

video_id                    0
trending_date               0
title                       0
channel_title               0
category_id                 0
publish_time                0
tags                        0
views                       0
likes                       0
dislikes                    0
comment_count               0
thumbnail_link              0
comments_disabled           0
ratings_disabled            0
video_error_or_removed      0
description               612
dtype: int64

In [ ]:
df1['country'] = 'CA'

In [ ]:
df2['country'] = 'US'

In [ ]:
df3['country'] = 'GB'

In [ ]:
df = pd.concat([df1, df2])

In [ ]:
df.shape

(120746, 17)

In [ ]:
df = pd.concat([df, df3])

In [ ]:
df.head()

video_id  ... country
0  n1WpP7iowLc  ...      CA
1  0dBIkQ4Mz1M  ...      CA
2  5qpjK5DgCt4  ...      CA
3  d380meD0W0M  ...      CA
4  2Vv-BfVoq4g  ...      CA

[5 rows x 17 columns]

In [ ]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
%matplotlib inline

In [ ]:
from sklearn.metrics import silhouette_score

In [ ]:
dfx = df[['views',	'likes',	'dislikes',	'comment_count']]

In [ ]:
dfx.head()

views    likes  dislikes  comment_count
0  17158579   787425     43420         125882
1   1014651   127794      1688          13030
2   3191434   146035      5339           8181
3   2095828   132239      1989          17518
4  33523622  1634130     21082          85067

In [ ]:
from sklearn.preprocessing import normalize
dfx = normalize(dfx)
dfx = pd.DataFrame(dfx, columns= ['views',	'likes',	'dislikes',	'comment_count'])
dfx.head()

views     likes  dislikes  comment_count
0  0.998919  0.045841  0.002528       0.007328
1  0.992080  0.124951  0.001650       0.012740
2  0.998950  0.045710  0.001671       0.002561
3  0.997980  0.062969  0.000947       0.008342
4  0.998811  0.048688  0.000628       0.002535

In [ ]:
dfx.shape

(120746, 4)

In [ ]:


for i in range(10):
    kmeans1 = KMeans(n_clusters=(i+2)).fit(dfx)
    print(silhouette_score(dfx,kmeans1.labels_),'-',i+2,' Clusters','\n')
#stopped after 6 clusters as coeff was decreasing and took over 30 mins

0.607984533965712 - 2  Clusters 

0.547874829001173 - 3  Clusters 

0.5123078897133884 - 4  Clusters 

0.4905072715448214 - 5  Clusters 

0.464424180493831 - 6  Clusters 



KeyboardInterrupt: ignored

0.607984533965712 - 2  Clusters 

0.547874829001173 - 3  Clusters 

0.5123078897133884 - 4  Clusters 

0.4905072715448214 - 5  Clusters 

0.464424180493831 - 6  Clusters 

In [ ]:
kmeans = KMeans(n_clusters=2).fit(dfx)

In [ ]:
centroids = kmeans.cluster_centers_
print(centroids)

[[0.9996655  0.02125493 0.00148399 0.00339411]
 [0.99677725 0.07416669 0.00161711 0.00924766]]


In [ ]:
kmeans.labels_.astype(float)

array([0., 1., 0., ..., 0., 0., 0.])

In [ ]:
dfx['cluster'] = kmeans.labels_

In [ ]:
dfx.head()

views     likes  dislikes  comment_count  cluster
0  0.998919  0.045841  0.002528       0.007328        0
1  0.992080  0.124951  0.001650       0.012740        1
2  0.998950  0.045710  0.001671       0.002561        0
3  0.997980  0.062969  0.000947       0.008342        1
4  0.998811  0.048688  0.000628       0.002535        1

Random Forest

In [ ]:
from sklearn.model_selection import train_test_split

X=dfx[['views',	'likes',	'dislikes',	'comment_count']]  # Features
y=dfx['cluster']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

y_pred=rfc.predict(X_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9997101449275362


In [ ]:
feature_imp = pd.Series(rfc.feature_importances_,index=X_train.columns).sort_values(ascending=False)
feature_imp

likes            0.570715
views            0.393463
comment_count    0.034070
dislikes         0.001751
dtype: float64

Likes and Views are most important columns

## RNN-LSTM-KERAS-NLTK [15 Marks]

#### This question is on the same dataset but separate from the previous. Now consider the 3 datasets again. 

#### The Data contains Category-ids as a column. Imagine these are the unique classification labels of the data.You may have to combine all the data before getting all the categories.

#### Now Create a model using RNN-LSTM-KERAS + NLTK to form a Deep Learning model. Choose the hyperparameters as per your analysis and model. Only category ids (as output) and Description (as input text) is to be taken for this model.

#### Use GPU to reduce the time for the computation process.

#### Find the Validation Accuracy after dividing you dataset into 80% training and 20% test set. Use 30% dropout to COMBAT OVERFITTING.

## COMPARE THE VALIDATION/TEST ACCURACY OF THE 2 MODELS AND BRIEFLY EXPLAIN WHICH ONE DO YOU THINK COULD BE USED IN WHICH CASE [5 MARKS]

In [ ]:
df.head()

video_id  ... country
0  n1WpP7iowLc  ...      CA
1  0dBIkQ4Mz1M  ...      CA
2  5qpjK5DgCt4  ...      CA
3  d380meD0W0M  ...      CA
4  2Vv-BfVoq4g  ...      CA

[5 rows x 17 columns]

In [ ]:
dfy = df[['category_id',	'description']]
dfy.head()

category_id                                        description
0           10  Eminem's new track Walk on Water ft. Beyoncé i...
1           23  STill got a lot of packages. Probably will las...
2           23  WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3           24  I know it's been a while since we did this sho...
4           10  🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
dfy['description']=dfy['description'].astype(str)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
import nltk
import re
from sklearn.model_selection import train_test_split
import string

stopwords = nltk.corpus.stopwords.words('english')

def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [word for word in tokens if word not in stopwords]
    return text

dfy['clean_text'] = dfy['description'].apply(lambda x: clean_text(x))
dfy.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


category_id  ...                                         clean_text
0           10  ...  [eminems, new, track, walk, water, ft, beyoncé...
1           23  ...  [still, got, lot, packages, probably, last, an...
2           23  ...  [watch, previous, video, nnsubscribe, httpswww...
3           24  ...  [know, since, show, back, might, best, episode...
4           10  ...  [, httpsadgtytperfectn, httpsatlanticrytalbumn...

[5 rows x 3 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dfy['clean_text'],
                                                    dfy['category_id'], test_size=0.2)

In [ ]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)

In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import tensorflow

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train['clean_text'])
X_train_seq = tokenizer.texts_to_sequences(X_train['clean_text'])
X_test_seq = tokenizer.texts_to_sequences(X_test['clean_text'])

In [ ]:
# Pad the sequences so each sequence is the same length
X_train_seq_padded = pad_sequences(X_train_seq, 50)
X_test_seq_padded = pad_sequences(X_test_seq, 50)

In [ ]:
y_train['category_id'].unique()

array([24, 28, 22, 10,  1, 25, 19, 26, 27, 23, 17, 20, 15,  2, 43, 29, 30])

In [ ]:
y_train['category_id'].replace({1:1,2:2,10:3,15:4,17:5,19:6,20:7,22:8,23:9,24:10,25:11,
                            26:12,27:13,28:14,29:15,30:16,43:17},inplace=True)

In [ ]:
y_test['category_id'].replace({1:1,2:2,10:3,15:4,17:5,19:6,20:7,22:8,23:9,24:10,25:11,
                            26:12,27:13,28:14,29:15,30:16,43:17},inplace=True)

In [ ]:
y_train = np.array(y_train).reshape(-1,1)

In [ ]:
y_test = np.array(y_test).reshape(-1,1)

In [ ]:
y_train[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)

In [ ]:
y_train = tensorflow.keras.utils.to_categorical(y_train, 18)
y_test = tensorflow.keras.utils.to_categorical(y_test, 18)

In [ ]:
# Import the tools needed and define functions to calculate precision and recall
import keras.backend as K
from keras.layers import Dense, Embedding, LSTM
from keras.models import Sequential

def recall_m(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

def precision_m(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision

In [ ]:
# Construct our basic RNN model framework
model = Sequential()

model.add(Embedding(len(tokenizer.index_word)+1, 32))
model.add(LSTM(32, dropout=0.3, recurrent_dropout=0.3))
model.add(Dense(32, activation='relu'))
model.add(Dense(18, activation='softmax'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, None, 32)          8363392   
_________________________________________________________________
lstm_6 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_12 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_13 (Dense)             (None, 18)                594       
Total params: 8,373,362
Trainable params: 8,373,362
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy', precision_m, recall_m])

In [ ]:
# Fit the RNN
history = model.fit(X_train_seq_padded, y_train, 
                    batch_size=512, epochs=10,
                    validation_data=(X_test_seq_padded, y_test))

Epoch 1/10
189/189 [==============================] - 53s 270ms/step - loss: 2.3566 - accuracy: 0.2936 - precision_m: 0.2313 - recall_m: 0.0606 - val_loss: 0.9812 - val_accuracy: 0.6525 - val_precision_m: 0.9417 - val_recall_m: 0.5072
Epoch 2/10
189/189 [==============================] - 52s 273ms/step - loss: 0.7510 - accuracy: 0.7756 - precision_m: 0.9605 - recall_m: 0.6361 - val_loss: 0.3881 - val_accuracy: 0.9022 - val_precision_m: 0.9716 - val_recall_m: 0.8496
Epoch 3/10
189/189 [==============================] - 50s 265ms/step - loss: 0.2895 - accuracy: 0.9231 - precision_m: 0.9768 - recall_m: 0.8868 - val_loss: 0.2643 - val_accuracy: 0.9334 - val_precision_m: 0.9728 - val_recall_m: 0.9137
Epoch 4/10
189/189 [==============================] - 49s 260ms/step - loss: 0.1633 - accuracy: 0.9551 - precision_m: 0.9847 - recall_m: 0.9384 - val_loss: 0.2291 - val_accuracy: 0.9429 - val_precision_m: 0.9752 - val_recall_m: 0.9297
Epoch 5/10
189/189 [==============================] - 50s 26

Since we have an output column "category ID", useing this method (RNN + .... + NLTK) is good at using the description to predict category. Potential uses could be to use description to screen content to prevent children from seeing content not recomended for children.

For random forest + clustering, we can use it to distinguish videos among the 2 clusters. Potential levels assigned for cluster 1 and 2 could be "high view to like ratio" and "low view to like ratio". This ratio could be used to predict bots who only watches videos but do not like or subscribe